version: '3'
services:
  itip-api:
    build:
      context: .
    image: "zate75/itip:itip-api"
    container_name: itip-api
    command: ["/opt/bitnami/scripts/redis/run.sh", "&", "/itip/itip", "&"]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 8080:8080
      - 6379
    user: root
    networks:
      - itip
    restart: on-failure

networks: 
  itip:            
